version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        image: laravel-app
        ports:
            - "9000:9000"
        networks:
            - app_network
        volumes:
            - .:/var/www
            - /var/www/node_modules
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped

        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - app_network
        volumes:
            - mysql-data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - app_network
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: redis
        networks:
            - app_network

volumes:
    mysql-data:

networks:
    app_network:
        driver: bridge
